### ISSUE TITLE
Cool Stuff

### ISSUE THREAD

**Issue by GeorgeNs** [x42/darc.lv2#1]
That's cool! Linux users really need a compressor like that.
I 'd wish to see a really transparent multiband compressor  one day as well,
thanks Robin for all the stuff in github!

**Comment by x42** [comment]
You're very welcome! I don't have any immediate plans for a multiband compressor, but that may happen someday. 

Meanwhile lsp-plugins offers one that is free/libre software, featuring a reasonable x-over stage and without phase-smearing. recent zam-plugins as well.  Personally I prefer harrison's XT-MC.lv2 but that's non-free.

**Comment by x42** [comment]
Not really an issue, so closing this. Thanks for the flowers!

**Comment by GeorgeNs** [comment]
Thanks a lot! Yes I know XT-MC(using the demo version) because i am a mixbus32c supporter and it is great,but it's not open source :(... BTW there is also AVA,which looks pretty similar to MC,but I don't know if the algorithm inside is the same(?)
