### ISSUE TITLE
commandline options

### ISSUE THREAD

**Issue by Axel-Erfurt** [x42/darc.lv2#5]
How can I start it with initial values, for example ratio 3 and treshold -24 ?

**Comment by x42** [comment]
run `x42-darc --portlist` , then for your example set port 3 (threshold) to -24, and port 4 (ratio) to 1:3

```
x42-darc -p 3:-24 -p 4:0.667
```

The parameter for the ratio is in the range [0..1] = (1 - compression-ratio).  This allows for ratios 1:1 to 1:inf (hard limit) to be represented.  So in your case  (1 - 1/3) = 0.6666...

**Comment by x42** [comment]
PS. If you use the plugin version, you can use presets provided by the host.

**Comment by Axel-Erfurt** [comment]
Thank you very much.
